Кулініч Владислав


Вступ до машинного навчання. Елементи лінійної алгебри.

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створити матрицю 3*3 заповнити її цілими випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1,6,size=(3,3))
matrix

array([[2, 1, 2],
       [5, 2, 5],
       [5, 5, 1]])

2. обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(3.999999999999999)

3. знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(5000)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(5000)

4. Знайти суму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(28)

5. Обчислити найбільший ,найменший елементи

In [ ]:
max_element = np.max(matrix)

print("найбільший елемент матриці:",max_element )

min_element = np.min(matrix)

print("найменший елемент матриці:",min_element )

найбільший елемент матриці: 5
найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [ ]:
mean = np.mean(matrix)
print(" середнє значення елементів матриці:",mean )

 середнє значення елементів матриці: 3.111111111111111


7. Знайти матрицю ,що складена  з квадратних коренів.

In [ ]:
sqrt_matrix= np.sqrt(matrix)
print(" матриця квадратних коренів:")
print(sqrt_matrix)

 матриця квадратних коренів:
[[1.41421356 1.         1.41421356]
 [2.23606798 1.41421356 2.23606798]
 [2.23606798 2.23606798 1.        ]]


8. Обчислити суму елементів кожного рядка . Відповідь записати як вектор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
print("Cума елементів кожного рядка:")
print(row_sums)
#8 результати отримали вектор-стовпчик

Cума елементів кожного рядка:
[[ 5]
 [12]
 [11]]


9. Створити вектор , що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0,10,size=25)

print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[1 0 1 5 5 6 9 3 9 0 3 2 6 2 9 8 1 6 7 1 3 1 3 0 7]
Вектор після сортування за спаданням:
[9 9 9 8 7 7 6 6 6 5 5 3 3 3 3 2 2 1 1 1 1 1 0 0 0]


10. Знайти моду ,медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats
# Знаходимо моду
mode =stats.mode(vector)

# Знаходимо медіану
median= np.median(vector)

# Знаходимо середнє
mean = np.mean(vector)

# Знаходимо максимальне значення
max_value = np.max(vector)

# Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:",mode)
print("Медіана:",median)
print("Середнє:",mean)
print("Максимальне значення:",max_value)
print("Мінімальне значення:",min_value)


Мода: ModeResult(mode=np.int64(1), count=np.int64(5))
Медіана: 3.0
Середнє: 3.92
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4 ,заповнені числами від 1 до 10. Обчислити суму ,різницю ,поелементний добуток,частку.

In [ ]:
# Створюємо дві матриці 4*4 із випадкових чисел від 1 до 10
matrix1 = np.random.randint(1,11,size=(4,4))
matrix2 = np.random.randint(1,11,size=(4,4))

print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)

Матриця 1:
[[6 3 1 8]
 [8 8 8 7]
 [9 3 6 6]
 [1 7 6 8]]
Матриця 2:
[[ 6  2  9 10]
 [ 4  6  2  2]
 [ 6  9  8  8]
 [ 8  7  6  4]]


In [ ]:
# Обчислюємо суму матриць
matrix_sum= matrix1+matrix2

# Обчислюємо різницю матриць
matrix_diff= matrix1-matrix2

# Обчислюємо поелементний добуток матриць
matrix_product= matrix1*matrix2

# Обчислюємо поелементну частку матриць
#Для запобігання ділення на нуль,використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)

print("\nПоелементна частка матриць:")
print(matrix_division)



Сума матриць:
[[12  5 10 18]
 [12 14 10  9]
 [15 12 14 14]
 [ 9 14 12 12]]

Різниця матриць:
[[ 0  1 -8 -2]
 [ 4  2  6  5]
 [ 3 -6 -2 -2]
 [-7  0  0  4]]

Поелементний добуток матриць:
[[36  6  9 80]
 [32 48 16 14]
 [54 27 48 48]
 [ 8 49 36 32]]

Поелементна частка матриць:
[[1.         1.5        0.11111111 0.8       ]
 [2.         1.33333333 4.         3.5       ]
 [1.5        0.33333333 0.75       0.75      ]
 [0.125      1.         1.         2.        ]]


Висновок: У цій лабораторній роботі я закріпив базові навички роботи з масивами та матрицями, використовуючи елементи лінійної алгебри в середовищі Python. Виконані завдання допомогли краще зрозуміти принципи генерації числових послідовностей та операцій над ними, що є основою для подальшого вивчення машинного навчання.